    [build]
      base = "Frontend/powerlifting-frontend" # This tells Netlify to change working directory here
      command = "npm run build --no-lint"
      publish = "dist" # This must be RELATIVE to the 'base' directory

    [[redirects]]
      from = "/*"
      to = "/index.html"
      status = 200
      force = true
    