[build]
  base = "Frontend/powerlifting-frontend" 
  command = "npm install && npm run build --no-lint" 
  publish = "dist" 

[[redirects]]
  # This rule ensures all requests that are NOT for existing files
  # (like /js/app.js or /css/app.css) are redirected to index.html for Vue Router.
  # The ! is crucial.
  from = "/*"
  to = "/index.html"
  status = 200
  force = false # <-- CRITICAL CHANGE: Set force to false
  # You might also use 'from = "/!(assets|js|css)/*"' but 'force = false' is often sufficient
