    [build]
      # No 'base' directory defined here. Build will start from the repo root.
      command = "cd Frontend/powerlifting-frontend && npm run build --no-lint" # Navigate and build
      publish = "Frontend/powerlifting-frontend/dist" # Absolute path from repo root to published files

    [[redirects]]
      from = "/*"
      to = "/index.html"
      status = 200
      force = true
    